Add required argument of APISpec: openapi_version
Before this commit, running the sample code will throw:
    TypeError: __init__() missing 1 required positional argument: 'openapi_version'